export const ERROR_TYPES = {
  AUTHORIZATION_ERROR: 'AUTHORIZATION_ERROR',
  NOT_FOUND_ERROR: 'NOT_FOUND_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNKNOWN_REQUEST_ERROR: 'UNKNOWN_REQUEST_ERROR',
};
